src/components/input/search.js

This pull request fixes issue #17

Fix search input error: _onSubmit is not a function

---

gatsby-config.js
package-lock.json
package.json
src/components/card/searchResult/anime.js
src/components/card/searchResult/artist.js
src/components/card/searchResult/index.js
src/components/card/searchResult/theme.js
src/components/card/theme/index.js
src/components/tag/index.js
src/components/text/index.js
src/components/text/style.js
src/components/text/title.js
src/components/utils/songTitleWithArtists.js
src/styles/global.js
src/templates/anime.js
src/templates/video.js
src/theme/index.js

This is a collection of smaller code improvements:
- Fixed resource list being a row instead of a column
- Made text components inherit font color if not otherwise specified
- The `color` prop can be used to explicitly set the color of text (see below)
- Added custom ESLint config to prevent errors because of missing React imports
```js
import theme from "theme";
export default function ColoredText({ children }) {
return (
<Text color={theme.colors.secondaryTitle}>
{children}
</Text>
);
}
```

Smaller code improvements

---

gatsby-node.js
src/components/card/searchResult/index.js
src/components/navigation/season.js
src/components/navigation/year.js
src/pages/year.js
src/templates/season.js
src/templates/video.js
src/templates/year.js

* Also fixed a lint warning in video.js
Closes #25

#25 fix: Year overview pages didn't group the anime by season

---

.eslintignore
.eslintrc.js
package-lock.json
package.json
src/components/button/index.js
src/components/container/sidebar.js
src/components/descriptionList/index.js
src/pages/year.js
src/templates/anime.js

* Fixed line separators being CRLF instead of LF
Closes #21

#21 style: Added some simple linting rules

---

plugins/gatsby-source-animethemes/src/index.js
src/components/search/global.js
src/hooks/useSearch.js

* Increased API request delay on build.
* Improved search performance.

fix: Search endpoint results are now wrapped inside another object

---

package-lock.json
package.json
schema.graphql
src/components/button/Button.js
src/components/input/SearchInput.js
src/components/listbox/Listbox.js
src/components/search-filter/FilterGroup.js
src/components/search-filter/SeasonFilter.js
src/components/search-filter/SortBy.js
src/components/search-filter/YearFilter.js
src/components/search-filter/index.js
src/components/search/EntitySearch.js
src/components/search/GlobalSearch.js
src/lib/search.js
src/pages/design.js
src/templates/search.js
src/theme/index.js

* Also reworked list box behaviour and API.

feat: #8 Added search filters for anime searches

---

gatsby-browser.js
src/components/search/SearchAnime.js
src/components/search/SearchArtist.js
src/components/search/SearchTheme.js
src/templates/search.js

* Also fixed scroll restoration on search pages.

fix: Search pages don't infinitely re-render anymore

---

gatsby-browser.js
plugins/gatsby-source-animethemes-db/src/source-nodes.js
src/components/button/Button.js
src/components/navigation/Navigation.js
src/hooks/useCurrentSeason.js
src/lib/randomTheme.js
src/lib/search.js
src/pages/dev.js
src/pages/index.js
src/templates/series.js
src/utils/navigateToRandomTheme.js

* Added random theme and current season functionality.
* These were also added to the navigation.
* The new home page replaces the old index ("/") page which was now moved to "/dev".
* Anime on the series page are now sorted by their premiere date.
* Adjusted database and API queries according to changes on the back-end.

#13 feat: Added home page

---

.github/workflows/main.yml
src/components/listbox/Listbox.js

* Also attempt to fix GitHub pages build.

fix: Corrected listbox styling after build

---

package-lock.json
package.json
src/components/box/Box.js
src/components/button/Button.js
src/components/card/Card.js
src/components/card/ErrorCard.js
src/components/card/index.js
src/components/external-link/ExternalLink.js
src/components/footer/Footer.js
src/components/image/CoverImage.js
src/components/image/FullWidthImage.js
src/components/navigation/Navigation.js
src/components/navigation/Navigation.style.js
src/components/search/SearchAnime.js
src/components/search/SearchArtist.js
src/components/search/SearchEntity.js
src/components/search/SearchGlobal.js
src/components/search/SearchSeries.js
src/components/search/SearchStudio.js
src/components/search/SearchTheme.js
src/components/text/Text.js
src/layout/index.js
src/lib/search.js
src/pages/design.js
src/pages/dev.js
src/styles/global.js
src/templates/anime.js

* All buttons now have "aria-label" and title attributes.
* Errors while searching now get caught and displayed.
* External links now have "rel=noopener" set.
* Big images now have small images as fallback to reduce LCP time.
* Font is now preloaded and optional to reduce CLS.
* Removed moment.js from dependencies to reduce bundle size.

fix: Improved performance, stability and accessibility

---

package-lock.json
package.json
src/components/external-link/ExternalLink.js
src/components/listbox/Listbox.js
src/lib/search.js
src/pages/dev.js
src/templates/season.js

* Order of anime on seasonal pages is now alphabetically.
* Added "time since last build" back in using new library, now also with timezone.

fix: Fixed index API requests having scoped include parameter

---

src/components/navigation/Navigation.js
src/components/navigation/Navigation.style.js
src/components/text/Text.js
src/components/video-player/VideoPlayer.js
src/components/video-player/VideoPlayer.style.js
src/layout/index.js
src/pages/index.js
src/templates/video.js

* The mini player on mobile now has the ability to pause and close.
* The card for when videos can't be played is now seperated from the video player.
* Tweaked spacing on video page.

feat: New mini player on mobile

---

plugins/gatsby-source-animethemes-db/src/create-schema-customization.js
plugins/gatsby-source-animethemes-db/src/source-nodes.js
schema.graphql
src/components/card/AnimeSummaryCard.js
src/components/filter/AnimeThemeFilter.js
src/templates/season.js
src/templates/series.js
src/templates/studio.js
src/templates/year.js
src/utils/comparators.js

* Fixed studio page sort filter not working.
* Adjusted ordering of sort filter options on series page.

fix: Fixed theme ordering being random on multiple pages

---

src/components/card/ThemeSummaryCard.js
src/components/seo/SEO.js
src/pages/_document.js

* Also removed something I forgot.

fix: Re-implement theme hydration & lighthouse findings

---

src/components/utils/AspectRatio.js
src/components/video-player/VideoPlayer.js
src/lib/client/api.js
src/lib/server/animethemes/resolvers.js
src/pages/_app.js
src/pages/_document.js
src/pages/anime/[animeSlug]/[videoSlug]/index.js
src/pages/studio/[studioSlug]/index.js

* Fixed studio resources not showing on mobile.
* Added experimental SEO for videos.

fix: Re-added custom font and artist resources

---

src/components/box/Box.js
src/components/navigation/Navigation.style.js
src/components/toast/AnnouncementToast.js
src/components/toast/Toast.js
src/components/toast/index.js
src/lib/client/announcement.js
src/lib/server/animethemes/resolvers.js
src/lib/server/animethemes/type-defs.js
src/pages/_app.js
src/pages/dev.js
src/pages/index.js
src/theme/index.js
src/utils/gaps.js

* Re-added page count on /dev page.
* Made navigation sticky.
* Added navigation fade in animation on mobile.
* Added style helper for modern gap CSS property.

feat: Added announcement toast

---

src/components/toast/AnnouncementToast.js
src/hooks/useSetting.js
src/lib/server/animethemes/resolvers.js
src/pages/dev.js
src/utils/settings.js

* Added setting to disable announcements.

fix: Fixed soft deleted entries still showing up

---

next.config.js
public/site.webmanifest
src/components/index/AlphabeticalIndex.js
src/components/index/index.js
src/components/text/Text.js
src/pages/anime/[animeSlug]/index.js
src/pages/artist/[artistSlug]/index.js
src/pages/index/anime.js
src/pages/index/artist.js
src/pages/index/series.js
src/pages/index/studio.js
src/pages/studio/[studioSlug]/index.js
src/utils/comparators.js

* Fixed order of description lists.

feat: Added static index pages

---

src/components/switcher/Switcher.js
src/pages/anime-awards.js

* Re-added animation for state transitions to switcher.

feat: Added /r/anime Awards page

---

src/components/index/AlphabeticalIndex.js

* Added hover text to summary card titles.
* Added event overview page.
* Added "Events" and "My Profile" buttons to home page.
* Moved event pages to new namespace.
* "My Profile" button in navigation now collapses to icon on smaller viewports.
* Sidebar container now switches to one column layout at a wider viewport.
* Fixed switcher animation.
* Replaced lodash with lodash-es for smaller bundle size.
* Bumped some dependencies.

feat: Added expandable theme view to anime summary card

---

src/components/card/AnimeSummaryCard.js
src/components/toast/PlaylistAddToast.js
src/components/utils/SongTitle.js
src/components/utils/SongTitleWithArtists.js
src/components/utils/index.js
src/components/video-player/VideoPlayer.js
src/context/localPlaylistContext.js
src/context/toastContext.js
src/lib/client/search.js
src/lib/server/animethemes/resolvers.js
src/lib/server/animethemes/type-defs.js
src/pages/anime/[animeSlug]/[videoSlug]/index.js
src/pages/page/[...pageSlug].js
src/utils/comparators.js
src/utils/markdownToHtml.js

* Added h3 to table of contents on document pages.
* Fixed missing song titles at multiple places.
* Fixed theme group display on video page.
* Fixed missing resolvers for artist members and groups.

fix: Songs can now be null

---

src/components/card/ThemeSummaryCard.js
src/context/localPlaylistContext.js
src/context/watchHistoryContext.js
src/pages/_app.js
src/pages/profile/playlist/index.js

- Added feature to refresh the local playlist.
- Themes are now re-fetched from the API before being added to the history or playlist.

fix: Fixed local storage getting filled up with unneeded data

---

src/components/featured-theme/FeaturedTheme.js
src/lib/client/randomGrill.js
src/pages/_app.js
src/pages/anime/[animeSlug]/index.js
src/pages/profile/index.js
src/utils/settings.js

* Added setting for revalidation token.
* Re-added revalidation interval for anime pages.

feat: Grills are now fetched from the API

---

src/components/card/ThemeDetailCard.style.js
src/components/navigation/SearchNavigation.js
src/components/search/SearchAnime.js
src/components/search/SearchArtist.js
src/components/search/SearchSeries.js
src/components/search/SearchStudio.js
src/components/search/SearchTheme.js
src/components/utils/Performances.js
src/pages/api/revalidate.js

* Fixed search filters sharing the same session storage key leading to overlap issues.
* Improved alignment of text inside theme detail cards.
* Made performances in song title expandable.
* Added base path to revalidate path.

fix: Fixed searching single resources not working

---

src/lib/client/randomGrill.js
src/lib/common/animethemes/api.js
src/lib/common/animethemes/resolvers.js
src/lib/common/animethemes/type-defs.js
src/pages/artist/[artistSlug]/index.js
src/pages/index.js

* Fixed recent themes not being ten entries.
* Fixed "Performed As" filter on artist page.

fix: Removed hardcoded /api from API URL

---

src/components/card/ThemeDetailCard.tsx
src/components/image/StudioCoverImage.tsx
src/components/input/Input.tsx
src/components/navigation/Navigation.style.ts
src/components/text/Text.ts
src/components/video-player/VideoPlayer.style.ts
src/components/video-player/VideoPlayer.tsx
src/generated/graphql.ts
src/lib/client/randomTheme.ts
src/lib/common/animethemes/api.ts
src/lib/common/animethemes/resolvers.ts
src/lib/common/animethemes/type-defs.ts
src/pages/anime/[animeSlug]/[videoSlug]/index.tsx
src/pages/api/revalidate.ts
src/pages/artist/[artistSlug]/index.tsx
src/pages/event/[bracketSlug]/index.tsx
src/styles/global.ts
src/styles/mixins.ts
src/utils/comparators.ts
src/utils/config.js
src/utils/devLog.ts
src/utils/settings.ts

* Added support for "as" field of artist memberships.
* Bracket pages no longer get prebuilt.
* Fixed wrong order of theme entries.
* Fixed studio cover background on studio page.
* Fixed color theme selectors.
* Fixed wrong alignment of "My Profile" on mobile navigation.
* Fixed very long song titles not wrapping correctly.
* Fixed play random feature.
* Fixed manual rebuilding.

feat: Added audio mode

---

src/components/card/AnimeSummaryCard.tsx
src/components/card/ThemeSummaryCard.tsx
src/components/video-player/VideoPlayer.style.ts
src/components/video-player/VideoPlayer.tsx
src/lib/client/randomTheme.ts

fix: Fixed audio mode for mobile background player

---

src/components/form/Input.tsx
src/components/navigation/Navigation.style.ts
src/components/video-script/VideoScript.tsx
src/generated/graphql.ts
src/pages/about/dump.tsx
src/pages/anime/[animeSlug]/[videoSlug]/index.tsx
src/pages/wiki/[...pageSlug]/index.tsx
src/styles/global.ts
src/styles/mixins.ts
tsconfig.json

* Improved encoding script download.

fix: Fixed download dump button on mobile

---

src/components/card/PlaylistSummaryCard.tsx
src/components/dialog/Dialog.tsx
src/components/dialog/PlaylistAddDialog.tsx
src/components/dialog/PlaylistRemoveDialog.tsx
src/components/dialog/PlaylistTrackAddDialog.tsx
src/components/dialog/RegisterDialog.tsx
src/components/toast/PlaylistRemoveToast.tsx
src/generated/graphql.ts
src/lib/client/search.ts
src/pages/profile/index.tsx

* Added action to delete playlists.
* Added playlist add action to track add dialog.
* Fixed global search.
* Fixed busy state of register dialog.
* Fixed message that shows when no playlist are available.
* Improved error handling when adding playlists.

feat: Various improvements to playlist support

---

src/components/card/PlaylistSummaryCard.tsx
src/components/dialog/PasswordChangeDialog.tsx
src/components/dialog/RegisterDialog.tsx
src/components/navigation/SearchNavigation.tsx
src/components/search/SearchGlobal.tsx
src/components/search/SearchPlaylist.tsx
src/components/utils/Busy.tsx
src/generated/graphql.ts
src/hooks/useAuth.ts
src/lib/client/axios.ts
src/lib/client/search.ts
src/lib/common/animethemes/api.ts
src/lib/common/animethemes/type-defs.ts
src/pages/profile/index.tsx
src/pages/search/[entity]/index.tsx

* Added password change dialog.
* Added links to terms of service and privacy policy to register dialog.
* Added notification on profile page when user has not verified their email yet.
* Added action to resend the verification email.
* Adjusted layout of profile page.
* Playlist summary cards can now include the owner.

feat: Add support for searching playlists

---

src/generated/graphql.ts
src/lib/common/animethemes/resolvers.ts
src/lib/common/animethemes/type-defs.ts
src/pages/profile/index.tsx

* Added role badges on profile page.
* Added special welcome message for new users.

feat: Add support for role color

---

package-lock.json
package.json
src/components/button/IconTextButton.tsx
src/components/card/PlaylistSummaryCard.tsx
src/components/dialog/LoginDialog.tsx
src/components/dialog/PlaylistTrackAddDialog.tsx
src/components/navigation/Navigation.style.ts
src/components/navigation/Navigation.tsx
src/components/switcher/Switcher.tsx
src/components/utils/HorizontalScroll.ts
src/components/video-player-2/ProgressBar.tsx
src/components/video-player-2/VideoPlayer2.style.ts
src/components/video-player-2/VideoPlayer2.tsx
src/context/playerContext.ts
src/generated/graphql.ts
src/lib/client/search.ts
src/lib/common/animethemes/resolvers.ts
src/lib/common/animethemes/type-defs.ts
src/pages/_app.tsx
src/pages/anime/[animeSlug]/[videoSlug]/index.tsx
src/pages/index.tsx
src/pages/playlist/[playlistId]/index.tsx
src/pages/profile/index.tsx

* Redesigned the navigation.
* Removed the mobile navigation toggle.
* Made the background transparent when page is not scrolled.
* Made buttons collapse to icons on mobile.
* Made the logo smaller.
* Added track count to playlist summary card.
* Fixed playlist page only displaying 15 tracks.
* Added option to remember login.
* Added "Most Viewed" section to home page.

feat: Started work on the new video player

---

src/components/dialog/ForgotPasswordDialog.tsx
src/components/dialog/PasswordResetDialog.tsx
src/components/featured-theme/FeaturedTheme.tsx
src/hooks/useAuth.ts
src/pages/playlist/[playlistId]/index.tsx
src/pages/profile/reset-password/index.tsx
src/theme/colors/index.ts

* Added ranking mode to playlists.

feat: Added forgot password function

---

src/components/index/AlphabeticalIndex.tsx
src/lib/client/axios.ts
src/pages/_app.tsx
src/pages/anime/index.tsx
src/pages/artist/index.tsx
src/pages/playlist/[playlistId]/index.tsx
src/pages/series/index.tsx
src/pages/studio/index.tsx

* Improved page transition when opening video player for the first time.
* Disabled prefetching for index pages.

feat: Added shuffle feature for playlists

---

src/components/video-player-2/VideoPlayer2.style.ts
src/components/video-player-2/VideoPlayerBar.tsx
src/pages/anime/[animeSlug]/[videoSlug]/index.tsx
src/pages/year/[year]/[season]/index.tsx
src/pages/year/[year]/index.tsx

* Fixed season order on season and year pages.
* Fixed overflow issue with video scripts.

feat: Added download option to share menu

---

src/components/utils/PageRevalidation.tsx
src/components/video-player/VideoPlayer.tsx

* Added back last update date on pages for everyone to see.

fix: Fixed play next not working with disabled autoplay

---

.husky/pre-commit
package-lock.json
package.json
src/lib/client/search.ts

fix: Fixed search request missing a field

---

src/components/button/VideoButton.tsx
src/components/video-player/VideoPlayerBar.tsx
src/context/playerContext.ts
src/pages/_app.tsx
src/utils/createVideoSlug.ts

* Fixed playing indicator on video buttons.

fix: Fixed video page not loading if the same video was played before

---

package-lock.json
package.json
src/components/dialog/PlaylistTrackAddDialog.tsx
src/components/form/TextArea.tsx
src/components/menu/ThemeMenu.tsx
src/components/video-player/VideoPlayerBar.tsx
src/components/video-player/VideoPlayerOverlay.tsx
src/generated/graphql.ts
src/lib/common/animethemes/resolvers.ts
src/lib/common/animethemes/type-defs.ts
src/pages/_app.tsx
src/pages/playlist/[playlistId]/index.tsx
src/styles/global.ts

* Added watch list actions to theme menu.
* Restructured theme and video menus.
* Changed some icons.
* Improved frontend performance of the playlist page.

feat: Add support for playlist descriptions

---

src/components/navigation/SearchNavigation.tsx
src/components/video-player/VideoPlayer.tsx
src/utils/createVideoSlug.ts

* Fixed weird behavior when dragging the mini player.
* Fixed transition between mini and normal player.
* Fixed too many prefetches on search page.

fix: Fixed video player not changing video in some cases

---

src/components/card/ThemeDetailCard.tsx
src/components/card/VideoSummaryCard.tsx
src/components/dialog/PlaylistTrackAddDialog.tsx
src/components/footer/Footer.tsx
src/components/menu/ThemeMenu.tsx
src/components/video-player/VideoPlayerBar.tsx
src/components/video-player/VideoPlayerOverlay.tsx
src/generated/graphql-resolvers.ts
src/generated/graphql.ts
src/lib/client/search.ts
src/lib/common/animethemes/api.ts
src/lib/common/animethemes/resolvers.ts
src/lib/common/animethemes/type-defs.ts
src/lib/common/animethemes/types.ts
src/pages/playlist/[playlistId]/index.tsx

* Added link to API docs to footer.
* Fixed global search returning wrong theme groups.

feat: Added support for entries in playlist tracks

---

src/components/dialog/ShuffleDialog.tsx
src/components/navigation/SearchNavigation.tsx
src/components/search-filter/SearchFilterMediaFormat.tsx
src/components/video-player/VideoPlayer.tsx
src/components/video-player/VideoPlayerOverlay.tsx
src/context/playerContext.ts
src/hooks/useMouseRelax.ts
src/lib/client/randomTheme.ts
src/lib/client/search.ts
src/pages/_app.tsx
src/pages/anime/[animeSlug]/[videoSlug]/index.tsx

* Added media format filter to shuffle.
* Added missing media formats to filter (for both search and shuffle).
* Improved mouse relax system.
* Fixed media format not displaying on global search.

feat: Added repeat toggle for watch lists

---

src/components/image/MultiCoverImage.tsx
src/generated/graphql-resolvers.ts
src/generated/graphql.ts
src/lib/common/animethemes/resolvers.ts
src/lib/common/animethemes/type-defs.ts
src/lib/common/animethemes/types.ts
src/pages/[...pageSlug]/index.tsx
src/pages/anime/[animeSlug]/index.tsx
src/pages/artist/[artistSlug]/index.tsx
src/pages/index.tsx
src/utils/extractImages.ts
src/utils/extractMultipleImages.ts
src/utils/serializeMarkdown.ts

* Artist `information` field;
* ArtistMember `notes` field;
* Multiple artist covers.

feat: added new artist features
